<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>DbSetup</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<!-- MSSQL -->
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
		<!-- MySQL -->
		<PackageReference Include="MySql.Data" Version="9.1.0" />
	</ItemGroup>

	<!-- Kopiraj SQL fajlove pored exe pri build-u -->
	<ItemGroup>
		<Content Include="config.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="schema_mssql.sql">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="schema_mysql.sql">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="seed.sql">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>