<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="config.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="config.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CoworkingApp.BusinessLogic\CoworkingApp.BusinessLogic.csproj" />
  </ItemGroup>

</Project>
